server:
  port: 8086

spring:
  application:
    name: NOTIFICATION-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/parkease_notification
    username: root
    password: 8770B26@k
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: agrawalkhushi267@gmail.com
    password: nriijxktqujbwxhc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost

  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0.1