server:
  port: 8083

spring:
  application:
    name: spot-service

  datasource:
    url: jdbc:mysql://localhost:3306/parkease_spot
    username: root
    password: 8770B26@k

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    prefer-ip-address: true
