server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/bookings/**

        - id: spot-service
          uri: lb://SPOT-SERVICE
          predicates:
            - Path=/spots/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: parkinglot-service
          uri: lb://PARKINGLOT-SERVICE
          predicates:
            - Path=/lots/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notify/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**


      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8084"   # 🔥 Swagger UI
              - "http://localhost:5173"   # frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


