server:
  port: 8084

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/parkease_booking
    username: root
    password: 8770B26@k

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    prefer-ip-address: true